### ISSUE TITLE
Unable to parse string / invalid character U

### ISSUE THREAD

**Issue by franzem** [arjunmehta/node-sqldump-to-json#45]
Hi, 

trying to use your library but I am getting this error message. 

Unable to parse string 
SyntaxError: JSON5: invalid character 'U' at 1:310

I suspect it has something to do with UTF-8 encoding. Do you support UTF-8?

**Comment by franzem** [comment]
found the problem, it wasn't a UTF-8 thing. 

for some unknown reason, mysqldump was outputting nulls as NULL as well as null, and JSON5 was complaning about the 'U' from NULL. 

the solution was to pipe in a sed to replace the NULL with null like this:

mysqldump <> | sed 's/NULL/null/g' | sqldump-to

**Comment by arjunmehta** [comment]
@franzem I'm so sorry to have only seen this now. I'm glad you were able to find a workaround, but it sounds like a not ideal solution for the long term :D 

I've put up a PR https://github.com/arjunmehta/sqldump-to/pull/51/files but I'd like to write some tests/test some more.

Thanks for this message, and I'm sorry I'm getting to this so late.
